### ISSUE TITLE
プルアップ抵抗の抵抗値について教えてください。

### ISSUE THREAD

**Issue by hiro0312** [takao-t/piradio#10]
初めまして。

以下について教えてください。

> GPIOに繋ぐスイッチ5個(PUSH ON) プルアップ抵抗5個(*) 基本は5個ですが最低2個で操作することができます。

これはタクトスイッチの一方の足をGNDへ。もう一方の足を抵抗を介してGPIOに繋ぐという理解で
間違ってないでしょうか？
その場合の抵抗値を教えてください。

どうぞよろしくお願い致します。

因みに Pirate Audio を使う小さい方は無事に完成して rdiko聴取を楽しめております。

**Comment by takao-t** [comment]
プルアップは下図のようにつなぎます。抵抗値は適当でかまわないのですが、10kΩ程度でいいかと思います。手持ちの適当なのを使ってください。

Vcc(3.3V)
|
R
|
+---- GPIO
|
SW
|
GND

**Comment by hiro0312** [comment]
早速のお返事ありがとうございます。
具体的な配線例で教えていただきたいのですが、
下記の画像で
https://fabble.cc/nxshg/chirimenpushbutton/slideshow
1番PIN ---> GND
3番PIN ---> GPIO
4番PIN <--- R(10k) <--- Vcc(3.3V)

つまり スイッチを押してないとき(平時)は GPIO に 10K の抵抗を介して常に 3.3V 以下の電圧がかかっていて、
スイッチを押したときに GPIO が 0V になる。
このような理解で問題ないでしょうか？

そうであるなら、何故 Vcc(3.3V) から GPIO までの抵抗が5個必要なのでしょうか？
例えば Vcc(3.3V) から線を引き出して抵抗を付け、その先を5股に分けて GPIO に繋ぐのでは駄目なのでしょうか？

お手数をお掛けしますが教えてください。
よろしくお願い致します。

**Comment by takao-t** [comment]
3と4は同じなので、3にGPIO、4に抵抗でも、3にGPIOと抵抗をつけてもかまいません。

>その先を5股に分けて GPIO に繋ぐ
できません。これをやると1個のSWを押すと全部のSWを同時に押したことになります。
絵を書いてみてください。

**Comment by hiro0312** [comment]
お世話になります。

添付画像の様な絵の認識なのですが、
![fig_01](https://github.com/takao-t/piradio/assets/165967860/660ad852-3fe9-4d87-acd9-86bd3d719d46)
何処がどう間違っているのか教えてください。
この絵ではVccから引き出した線に抵抗を付けて3股に分岐しております。

1個のSWを押すと全部のSWを同時に押したことになるという理屈がどうしても解らないのですが・・・

よろしくお願いいたします。

**Comment by takao-t** [comment]
答えはご自分で書かれていると思いますが。。

GPIOのひとつをGNDと接続したら、どのようなことが起こりますか？

**Comment by hiro0312** [comment]
お世話になります。
スイッチの動作も、プルアップ抵抗を最低2個から操作可能なことも多くを理解できました。
お陰様で大きい方ももうすぐ完成させられそうです。

ありがとうございました。

**Comment by takao-t** [comment]
ではこの件はクローズします。
